# SPDX-FileCopyrightText: 2026 Ian Douglas Lawrence Norman McLean
# SPDX-License-Identifier: AGPL-3.0-or-later
# Values consumed somewhere but defined nowhere.
PREFIX lmnf: <https://metavacua.github.io/lm-normal-form/ns#>
SELECT (COUNT(?v) AS ?count) WHERE { ?v lmnf:undefined true }
